version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    ports:
      - "8112:1552"
    restart: unless-stopped
    volumes:
      - ./logs:/app/logs
    depends_on:
      - db

  db:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bangladesh_geocode
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - '33061:3306'
    volumes:
      - ./db-data:/var/lib/mysql

  prometheus:
    image: prom/prometheus
    ports:
      - '9090:9090'
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'

  grafana:
    image: grafana/grafana
    ports:
      - '3000:3000'
    volumes:
      - grafana-storage:/var/lib/grafana
    depends_on:
      - prometheus

volumes:
  grafana-storage:
  db-data:




# docker run -d -e "CONNECTION=user:password@tcp(db:3306)/bangladesh_geocode?charset=utf8mb4&parseTime=True&loc=Local" -e "SERVER_PORT=1552" -e "SERVER_URL=http://localhost:1552" -p 8112:1552 --name bangladesh_geocode