global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
- job_name: 'bangladesh_geocode'
  static_configs:
  - targets: [ 'host.docker.internal:1552' ] # Update port if different
  metrics_path: '/metrics'
